server:
  port: 8104
  servlet:
    contextPath: /reporting/api
management:
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: health,info,loggers,metrics
swagger:
  enabled: true
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} | marker=%marker |  clientId=%X{clientId} | level=%5p | thread=%thread | traceId=%X{traceId} spanId=%X{spanId} |  projectVersion=%X{projectVersion} |class=%class{15}.%L | msg="%.-50000m"%n'

spring:
  application:
    name: "reporting-xbc"
  webflux:
    base-path: /reporting/api
  security:
    oauth2:
      resourceserver:
        jwt:
          tenantLulo:
            issuer: https://lulobank.com.co
            private-key-value: classpath:private_key.pem
            public-key-value: classpath:public_key.pem
          tenantAWS:
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1WmBHEn0a/.well-known/jwks.json
            issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_1WmBHEn0a
            authorized-scope: internal_api/internal_transactions
  zipkin:
    baseUrl: http://lbk-nlb-sand-b4ae09a807e738b7.elb.us-east-1.amazonaws.com:9411/
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    dynamodb:
      endpoint: https://dynamodb.us-east-1.amazonaws.com
    s3:
      statement:
        name: "lbk-reporting-sand"
        directory: "statement/{0}/{1}/{2}/"
      statement-transient:
        name: "lbk-reporting-transient-sand"
        directory: "notification/pending_loan_statements/"
      digitalevidence:
        bucket:
          policies: lulo-terminos-y-condiciones-sand
          evidence: evidencia-digital-sand
    sqs:
      end-point: https://sqs.us-east-1.amazonaws.com
      listeners:
        application-events: https://sqs.us-east-1.amazonaws.com/848155883266/reportingEventsRx-sand
      queue:
        client-events-v2: https://sqs.us-east-1.amazonaws.com/848155883266/clientEventsV2-sand
        client-alerts-events: https://sqs.us-east-1.amazonaws.com/848155883266/clientAlerts-sand
      max-number-of-messages: 10

flexibility:
  sdk:
    url: http://flex-internal-nlb-sand-7780f47397c1c3fc.elb.us-east-1.amazonaws.com
    clientId: ABTr4YVFhas8Yfq1uGfR
    secret: fRrdj0JD1zDLLcPHpVkCsKRKPG5C4kafaTW5PUSy
