# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Trigger Pull Request execute test SonarQube

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job Circleci
        run: |
          echo "Execute job build"
          curl -X POST -H "Content-Type: application/json" -d '{"build_parameters": {"CIRCLE_JOB" : "build_and_test"}}' https://circleci.com/api/v1.1/project/github/piso19/reporting-xbc/tree/$GITHUB_HEAD_REF?circle-token=${{ secrets.CIRCLECI_TOKEN }}